
services:
  postgres_database:
    container_name: pg_db
    build:
      dockerfile: dockerfiles/Dockerfile_postgres
      context: .
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/sql:/dump-data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/pg_secret
      - POSTGRES_DB=poi_db
    secrets:
      - pg_secret
    ports:
      - 5432:5432
  
  notebook:
    container_name: spark_notebook
    build:
      dockerfile: dockerfiles/Dockerfile_notebook
      context: .
    environment:
      - NB_USER=poi_project
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=/usr/local/spark/jars/
    secrets:
      - api_auth_secret
      - snowflake_user
      - snowflake_secret
      - snowflake_account
    volumes:
      - ./src:/src
      - .:/home/poi_project/
      - ./data/raw:/home/poi_project/work/data/raw
    ports:
      - 8888:8888
      - 0.0.0.0:8000:8000
    # command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --NotebookApp.token='' --NotebookApp.password=''
    command: uvicorn src.api.data_api:app --app-dir src --reload

secrets:
   pg_secret:
     file: ./secrets/pg_secret.txt
   api_auth_secret:
     file: ./secrets/api_auth_secret.txt
   snowflake_user:
     file: ./secrets/snowflake_user.txt
   snowflake_secret:
     file: ./secrets/snowflake_secret.txt
   snowflake_account:
     file: ./secrets/snowflake_account.txt