FROM quay.io/jupyter/pyspark-notebook


USER root
RUN apt update -y && apt install -y libpq-dev python3-dev gcc g++ libssl-dev 

RUN apt update -y && apt install -y libpq-dev python3-dev gcc g++ libssl-dev 

WORKDIR /home/poi_project/
RUN chown -R 1000 /home/poi_project/

COPY requirements.txt .
RUN pip install -r requirements.txt 

COPY src/etl/postgresql-42.7.8.jar /usr/local/spark/jars/postgresql-42.7.8.jar

# RUN sudo chmod -R 777 app_data/
